"""Initial migration

Revision ID: 355dec0d603e
Revises: 
Create Date: 2026-07-27 12:56:15.412915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355dec0d603e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=True),
    sa.CheckConstraint("category IN ('Strength', 'Cardio', 'Flexibility', 'Balance')", name='exercise_category_valid'),
    sa.CheckConstraint('length(name) >= 3', name='exercise_name_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('date <= CURRENT_DATE', name='workout_date_not_future'),
    sa.CheckConstraint('duration_minutes > 0', name='workout_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('(reps IS NOT NULL OR duration_seconds IS NOT NULL)', name='reps_or_duration'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='duration_positive'),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name='reps_positive'),
    sa.CheckConstraint('sets IS NULL OR sets > 0', name='sets_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
